# Generated by Django 5.0.6 on 2024-06-23 02:41

from django.db import migrations

from ..fixtures import create_superuser


class Migration(migrations.Migration):

    dependencies = [
        ("{{ cookiecutter.project_slug }}_users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
